# Generated by Django 4.1.4 on 2023-01-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_desc_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(blank=True, default='这个人很懒，什么都没有写。', max_length=200, verbose_name='个人简介'),
        ),
    ]
