# Generated by Django 3.0.4 on 2021-10-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
